# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_deltaPDF', [dirname(__file__)])
        except ImportError:
            import _deltaPDF
            return _deltaPDF
        if fp is not None:
            try:
                _mod = imp.load_module('_deltaPDF', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _deltaPDF = swig_import_helper()
    del swig_import_helper
else:
    import _deltaPDF
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _deltaPDF.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _deltaPDF.SwigPyIterator_value(self)
    def incr(self, n=1): return _deltaPDF.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _deltaPDF.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _deltaPDF.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _deltaPDF.SwigPyIterator_equal(self, *args)
    def copy(self): return _deltaPDF.SwigPyIterator_copy(self)
    def next(self): return _deltaPDF.SwigPyIterator_next(self)
    def __next__(self): return _deltaPDF.SwigPyIterator___next__(self)
    def previous(self): return _deltaPDF.SwigPyIterator_previous(self)
    def advance(self, *args): return _deltaPDF.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _deltaPDF.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _deltaPDF.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _deltaPDF.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _deltaPDF.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _deltaPDF.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _deltaPDF.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _deltaPDF.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Line(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Line, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Line, name)
    __repr__ = _swig_repr
    def iterator(self): return _deltaPDF.Line_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _deltaPDF.Line___nonzero__(self)
    def __bool__(self): return _deltaPDF.Line___bool__(self)
    def __len__(self): return _deltaPDF.Line___len__(self)
    def pop(self): return _deltaPDF.Line_pop(self)
    def __getslice__(self, *args): return _deltaPDF.Line___getslice__(self, *args)
    def __setslice__(self, *args): return _deltaPDF.Line___setslice__(self, *args)
    def __delslice__(self, *args): return _deltaPDF.Line___delslice__(self, *args)
    def __delitem__(self, *args): return _deltaPDF.Line___delitem__(self, *args)
    def __getitem__(self, *args): return _deltaPDF.Line___getitem__(self, *args)
    def __setitem__(self, *args): return _deltaPDF.Line___setitem__(self, *args)
    def append(self, *args): return _deltaPDF.Line_append(self, *args)
    def empty(self): return _deltaPDF.Line_empty(self)
    def size(self): return _deltaPDF.Line_size(self)
    def clear(self): return _deltaPDF.Line_clear(self)
    def swap(self, *args): return _deltaPDF.Line_swap(self, *args)
    def get_allocator(self): return _deltaPDF.Line_get_allocator(self)
    def begin(self): return _deltaPDF.Line_begin(self)
    def end(self): return _deltaPDF.Line_end(self)
    def rbegin(self): return _deltaPDF.Line_rbegin(self)
    def rend(self): return _deltaPDF.Line_rend(self)
    def pop_back(self): return _deltaPDF.Line_pop_back(self)
    def erase(self, *args): return _deltaPDF.Line_erase(self, *args)
    def __init__(self, *args): 
        this = _deltaPDF.new_Line(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _deltaPDF.Line_push_back(self, *args)
    def front(self): return _deltaPDF.Line_front(self)
    def back(self): return _deltaPDF.Line_back(self)
    def assign(self, *args): return _deltaPDF.Line_assign(self, *args)
    def resize(self, *args): return _deltaPDF.Line_resize(self, *args)
    def insert(self, *args): return _deltaPDF.Line_insert(self, *args)
    def reserve(self, *args): return _deltaPDF.Line_reserve(self, *args)
    def capacity(self): return _deltaPDF.Line_capacity(self)
    __swig_destroy__ = _deltaPDF.delete_Line
    __del__ = lambda self : None;
Line_swigregister = _deltaPDF.Line_swigregister
Line_swigregister(Line)


def print_line(*args):
  return _deltaPDF.print_line(*args)
print_line = _deltaPDF.print_line
class PDF(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PDF, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PDF, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _deltaPDF.delete_PDF
    __del__ = lambda self : None;
    def pdfVal(self, *args): return _deltaPDF.PDF_pdfVal(self, *args)
PDF_swigregister = _deltaPDF.PDF_swigregister
PDF_swigregister(PDF)

class DeltaPDF(PDF):
    __swig_setmethods__ = {}
    for _s in [PDF]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DeltaPDF, name, value)
    __swig_getmethods__ = {}
    for _s in [PDF]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, DeltaPDF, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _deltaPDF.new_DeltaPDF(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _deltaPDF.delete_DeltaPDF
    __del__ = lambda self : None;
    def pdfVal(self, *args): return _deltaPDF.DeltaPDF_pdfVal(self, *args)
DeltaPDF_swigregister = _deltaPDF.DeltaPDF_swigregister
DeltaPDF_swigregister(DeltaPDF)

# This file is compatible with both classic and new-style classes.


