#!/bin/bash

# Must be made first
make -f Makefile.swig_matrix
make -f Makefile.swig_matrix3d
make -f Makefile.swig_matrix4d
make -f Makefile.swig_vector

shopt -s extglob
for i in `echo Makefile.swig_!(matrix|matrix3d|vector)`; do
    make -f `echo $i`
done
